version: "3.8"

services:
  postgres:
    container_name: gestao_meca_postgres
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_meca
  